/* File automatically generated; DO NOT edit! */

export const enum IngredientKey {
  ActiveDryYeast = "active-dry-yeast",
  AllPurposeWheatFlour = "all-purpose-wheat-flour",
  BakingSoda = "baking-soda",
  Bulgur = "bulgur",
  CarrierOil = "carrier-oil",
  Carrot = "carrot",
  Chickpea = "chickpea",
  CoconutOil = "coconut-oil",
  CornStarch = "corn-starch",
  Cucumber = "cucumber",
  Dill = "dill",
  DryFruitMix = "dry-fruit-mix",
  EssentialOil = "essential-oil",
  FishStock = "fish-stock",
  Garlic = "garlic",
  GranulatedSalt = "granulated-salt",
  GranulatedSugar = "granulated-sugar",
  GreekYogurt = "greek-yogurt",
  GroundBlackPepper = "ground-black-pepper",
  Honey = "honey",
  Leek = "leek",
  LimeJuice = "lime-juice",
  Mint = "mint",
  NutSeedMix = "nut-seed-mix",
  OatFlakes = "oat-flakes",
  OliveOil = "olive-oil",
  Parsley = "parsley",
  Potato = "potato",
  RoundOnion = "round-onion",
  Salmon = "salmon",
  StrongWheatFlour = "strong-wheat-flour",
  Tahini = "tahini",
  Tomato = "tomato",
  Water = "water",
  WholeMilk = "whole-milk",
  WholeRyeFlour = "whole-rye-flour",
  WholeWheatFlour = "whole-wheat-flour"
}
