/* File automatically generated; DO NOT edit! */

export const enum IngredientKey {
  ActiveDryYeast = "active-dry-yeast",
  AllPurposeWheatFlour = "all-purpose-wheat-flour",
  BakingSoda = "baking-soda",
  Bulgur = "bulgur",
  CarrierOil = "carrier-oil",
  CoconutOil = "coconut-oil",
  CornStarch = "corn-starch",
  Cucumber = "cucumber",
  DryFruitMix = "dry-fruit-mix",
  EssentialOil = "essential-oil",
  GranulatedSalt = "granulated-salt",
  GranulatedSugar = "granulated-sugar",
  Honey = "honey",
  LimeJuice = "lime-juice",
  Mint = "mint",
  NutSeedMix = "nut-seed-mix",
  OatFlakes = "oat-flakes",
  OliveOil = "olive-oil",
  Parsley = "parsley",
  RoundOnion = "round-onion",
  StrongWheatFlour = "strong-wheat-flour",
  Tomato = "tomato",
  Water = "water",
  WholeMilk = "whole-milk",
  WholeRyeFlour = "whole-rye-flour",
  WholeWheatFlour = "whole-wheat-flour"
}
